### ISSUE TITLE
One test isn't passing

### ISSUE THREAD

**Issue by alishinski** [iamamutt/datavyur#3]
So I made a bunch of small cleanup changes to the code to resolve all of the issues that were previously popping up, and I pushed those changes. But there is one remaining issue preventing the package from building properly, one test is failing. Here's the error that came up when checking the package: 

E  Running ‘testthat.R’ (1.9s)
   Running the tests in ‘tests/testthat.R’ failed.
   Last 13 lines of output:
      8. datavyur:::get_datavyu_info(...)
     
     ══ Failed tests ════════════════════════════════════════════════════════════════
     ── Failure (test-exported.R:134:3): horz concat is ordinal aligned and identical to ordinal import ──
     nrow(.data) not equal to `nrows`.
     1/1 mismatches
     [1] 2 - 155 == -153
     Backtrace:
         █
      1. └─datavyur:::data_frame_tests(...) test-exported.R:134:2
      2.   └─testthat::expect_equal(nrow(.data), nrows) test-exported.R:39:2
     
     [ FAIL 1 | WARN 10 | SKIP 0 | PASS 39 ]
     Error: Test failures
     Execution halted

For whatever reason when it compares the horizontally merged data to the result of ordinal_align() the former has 155 rows and the latter has 2. And I wasn't quite able to figure out why, so any thoughts @iamamutt ? If I comment out that test I could get it to build properly and submit it to CRAN, but it also seems like the test failing could be a real issue.

**Comment by jrosen48** [comment]
@iamamutt touching base on this again - any thoughts? Hoping we can get this lovely package onto CRAN!

**Comment by iamamutt** [comment]
Hi @jrosen48 . I fixed a line in the horizontal merging function. The test should pass now.

**Comment by jrosen48** [comment]
woo! thank you!
